fail_fast: true
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.282
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
  - repo: https://github.com/myint/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [--in-place, --pre-summary-newline, --close-quotes-on-newline]
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.2.0
    hooks:
      - id: pycln
        args: [-q, --all, --exclude, __init__.py]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: check-version
        name: check-version
        entry: sh -c "git diff --staged pyproject.toml | grep version"
        language: system
        pass_filenames: false
        always_run: true
